version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
      time: "19:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    groups:
      minor-patch-dependencies:
        update-types:
          - minor
          - patch
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "19:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    groups:
      minor-patch-dependencies:
        update-types:
          - minor
          - patch
